services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bexdb'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - "6379:6379"